export const GIT_COMMAND_NAMES = [
  'status',
  'statusPorcelain',
  'log',
  'branches',
  'commitDetails',
  'conflictTakeOurs',
  'conflictTakeTheirs',
  'conflictTakeDeleted',
  'conflictMarkResolved',
  'mergeContinue',
  'mergeAbort',
  'rebaseContinue',
  'rebaseAbort',
  'cherryPickContinue',
  'cherryPickAbort',
  'branch',
  'config',
  'remote',
  'tag',
  'forEachRef',
  'adoptRemoteTag',
  'fetch',
  'pull',
  'push',
  'checkout',
  'commit',
  'reset',
  'rm',
  'clean',
  'stash',
  'diff',
  'show',
  'add',
  'cherry-pick',
  'revert',
  'merge',
  'submoduleStatus',
  'submoduleUpdateInitRecursive',
  'submoduleSyncRecursive',
  'reflog',
  'forensicHistory',
] as const;

export type GitCommandName = (typeof GIT_COMMAND_NAMES)[number];

export const GIT_COMMAND_NAME_SET: ReadonlySet<GitCommandName> = new Set(GIT_COMMAND_NAMES);

export const MAX_ARGS_BY_GIT_COMMAND: Readonly<Partial<Record<GitCommandName, number>>> = {
  status: 2,
  statusPorcelain: 0,
  log: 3,
  branches: 0,
  commitDetails: 1,
  conflictTakeOurs: 1,
  conflictTakeTheirs: 1,
  conflictTakeDeleted: 1,
  conflictMarkResolved: 1,
  mergeContinue: 0,
  mergeAbort: 0,
  rebaseContinue: 0,
  rebaseAbort: 0,
  cherryPickContinue: 0,
  cherryPickAbort: 0,
  fetch: 8,
  pull: 6,
  push: 8,
  branch: 4,
  config: 3,
  remote: 4,
  tag: 6,
  forEachRef: 3,
  adoptRemoteTag: 2,
  checkout: 5,
  commit: 6,
  reset: 4,
  rm: 103,
  clean: 4,
  stash: 6,
  diff: 6,
  show: 6,
  add: 4,
  'cherry-pick': 3,
  revert: 5,
  merge: 4,
  submoduleStatus: 0,
  submoduleUpdateInitRecursive: 0,
  submoduleSyncRecursive: 0,
  reflog: 1,
  forensicHistory: 6,
};

export const isGitCommandName = (value: unknown): value is GitCommandName => typeof value === 'string' && GIT_COMMAND_NAME_SET.has(value as GitCommandName);
