import type { AppSettingsDto } from '@/types/appDtos';

export const DEFAULT_SETTINGS: AppSettingsDto = {
  theme: 'copper-night',
  language: 'de',
  autoFetchIntervalMs: 60_000,
  defaultBranch: 'main',
  confirmDangerousOps: true,
  commitTemplate: '',
  showSecondaryHistory: true,
  commitSignoffByDefault: false,
  autoUpdateEnabled: true,
  secretScanBeforePushEnabled: true,
  secretScanStrictness: 'medium',
  secretScanAllowlist: '',
  aiAutoCommitEnabled: false,
  aiProvider: 'ollama',
  aiCommitMessageStyle: 'conventional',
  aiCommitMessageLanguage: 'auto',
  ollamaBaseUrl: 'http://127.0.0.1:11434',
  ollamaModel: '',
  geminiModel: 'gemini-3-flash-preview',
  hasGeminiApiKey: false,
  githubOauthClientId: '',
  githubHost: 'github.com',
};
